config/routes.rb
Rails.application.routes.draw do

  get "customer/:id/order/:orderid", to: "order_items#show", as: "receipt"

  post 'create_checkout_session', to: 'payments#create_checkout_session'
  get 'success', to: 'payments#success'
  get 'cancel', to: 'payments#cancel'


  get "product", to: "product#index", as: "products_index"
  get "product/:id", to: "product#show", as: "product"
  get "customer/:customerid/order/:orderid/product/:id", to: "product#show", as: "receipt_view_product"
  get "product/:id/addtocart", to: "product#addToCart", as: "addtocart"

  get "customer/:id", to: "customers#show", as: "customer"
  post "customer/create", to: "customers#create", as: "create_customer"

  resources :customers, only: [:new, :create, :show]

  get "pages/login", to: "pages#login", as: "login"
  post "pages/login_check", to: "pages#login_check", as: "login_check"
  get "pages/logout", to: "pages#logout", as: "logout"
  get "pages/register", to: "pages#register", as: "register"
  get "pages/cart", to: "pages#cart", as: "cart"
  post "pages/cart", to: "pages#removeFromCart", as: "remove"
  patch "/cart/update_quantity", to: "pages#update_quantity"
  get "cart/update_province", to: "pages#update_province", as: "update_province"
  get "/cart/invoice/checkout", to: "pages#checkout", as: "checkout"
  get "pages/cart/invoice", to: "pages#invoice", as: "invoice"
  get "pages/about", to: "pages#about", as: "about"
  get "pages/contact", to: "pages#contact", as: "contact"


resources :products
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "product#index"
end

app/views/shared/_footer.html.erb
<div style="background-color: #3c4257ff; height:20vh; padding:30px; display:flex; align-items:flex-end; flex-direction:column;">
  <h1> <%= link_to "About", about_path, class: "about-contact" %></h1>

    
    <h1><%=link_to "Contact",contact_path, class:"about-contact"%></h1>
</div>

app/views/shared/_header.html.erb
<nav class="navbar is-link" role="navigation" aria-label="main navigation">
  <div class="navbar-menu">
    
    <div style="display: flex; margin:10px">
        <%= link_to "Home", root_path, class: "button is-primary", style:"height: 37px; display: flex; align-items: center; justify-content: center; color: white;"%>
      
      <% if session[:customer_id].present? %>
      
        <%= link_to "Profile", customer_path(session["customer_id"]), class: "button is-primary", style:"height: 37px; display: flex; align-items: center; justify-content: center; color: white;"%>
        <%= link_to "Logout", logout_path, class: "button is-primary", style:"height: 37px; display: flex; align-items: center; justify-content: center; color: white;"%>
        <%= link_to "Cart", cart_path, class: "button is-primary", style:"height: 37px; display: flex; align-items: center; justify-content: center; color: white;"%>
      
      <% else %>
       
        <%= link_to "Login", login_path, class: "button is-primary", style:"height: 37px; display: flex; align-items: center; justify-content: center; color: white;"%>
        <%= link_to "Register", register_path, class: "button is-primary", style:"height: 37px; display: flex; align-items: center; justify-content: center; color: white;"%>
      
      <% end %>
    </div>
    <!-- Hamburger menu for mobile -->
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarMenu" class="navbar-end" style="margin-top:10px; margin-right: 10px;">


    <%= form_with url: products_index_path, class: "control", method: :get, local: true , data: { turbo: false } do %>
      <%= text_field_tag :query, params[:query], class:"input", placeholder: "Search Product Names", style:"width: 300px; height: 37px" %>

      <%= select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name, params[:category_id]), include_blank: "All Categories"  %>

      <%= select_tag :date_filter, options_for_select([['Recently Added', 'new'], ['Recently Updated', 'update']], params[:date]), include_blank: "Select Date" %>
      
      <button type="submit" style="height:37px">Filter</button>
    <% end %>
    
        <%= link_to "Clear Filter", root_path, class: "button is-primary", style:"height: 37px; display: flex; align-items: center; justify-content: center; color: white;"%>
  </div>
</nav>