config/routes.rb
Rails.application.routes.draw do

  get "customer/:id/order/:orderid", to: "order_items#show", as: "receipt"

  post 'create_checkout_session', to: 'payments#create_checkout_session'
  get 'success', to: 'payments#success'
  get 'cancel', to: 'payments#cancel'


  get "product", to: "product#index", as: "products_index"
  get "product/:id", to: "product#show", as: "product"
  get "customer/:customerid/order/:orderid/product/:id", to: "product#show", as: "receipt_view_product"
  get "product/:id/addtocart", to: "product#addToCart", as: "addtocart"

  get "customer/:id", to: "customers#show", as: "customer"
  post "customer/create", to: "customers#create", as: "create_customer"

  resources :customers, only: [:new, :create, :show]

  get "pages/login", to: "pages#login", as: "login"
  post "pages/login_check", to: "pages#login_check", as: "login_check"
  get "pages/logout", to: "pages#logout", as: "logout"
  get "pages/register", to: "pages#register", as: "register"
  get "pages/cart", to: "pages#cart", as: "cart"
  post "pages/cart", to: "pages#removeFromCart", as: "remove"
  patch "/cart/update_quantity", to: "pages#update_quantity"
  get "cart/update_province", to: "pages#update_province", as: "update_province"
  get "/cart/invoice/checkout", to: "pages#checkout", as: "checkout"
  get "pages/cart/invoice", to: "pages#invoice", as: "invoice"
  get "pages/about", to: "pages#about", as: "about"
  get "pages/contact", to: "pages#contact", as: "contact"


resources :products
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "product#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  has_many :order_items, dependent: :nullify

  has_one_attached :image

  def self.ransackable_attributes(auth_object = nil)
    [ "id", "name", "description", "price", "in_stock", "category_id" ]
  end
  
  validates :name, presence:true
  validates :description, presence:true
  validates :price, presence:true, numericality:{only_integer: true,greater_than:0}
  validates :in_stock, presence:true, inclusion: { in: [true, false] }
  validates :category_id, presence:true,numericality:{only_integer: true,greater_than:0}
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
    @products = Product.all

    # apply search filter
    if params[:query].present?
      @products = @products.where("LOWER(name) LIKE ?", "%#{params[:query].downcase}%")
    end

    # apply category filter
    if params[:category_id].present?
      @products = @products.where(category_id: params[:category_id])
    end

    if params[:date_filter].present?
      if params[:date_filter] == 'new'
        @products = @products.where("created_at >= ?", 3.days.ago)
      elsif params[:date_filter] == 'update'
        @products = @products.where("updated_at >= ? AND DATE(updated_at) != DATE(created_at)", 3.days.ago)
      end
    end

    # paginate *after* filtering
    @products = @products.page(params[:page]).per(9)
  end


  def show
    @product = Product.find(params[:id])
    
      if params[:customerid].present? && params[:orderid].present?
        @customer = Customer.find(params[:customerid])
        @order = Order.find(params[:orderid])
        @mode = :order_context
      else
        @mode = :product_context
      end
  end

  def addToCart
    session[:cart] ||=[]
    @product = Product.find(params[:id])
    flash[:notice] = "#{@product.name} added to cart!"
    session[:cart] << { product_id: @product.id, quantity: params[:quantity].to_i, price: @product.price.to_f }
     puts session[:cart].inspect 
    redirect_to root_path
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/product/index.html.erb
<div style="min-height: 95vh;"><h1 class="title is-1" style="color: #1c4ecdff;">Products</h1>


  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>

  <% if flash[:alert] %>
    <p class="alert"><%= flash[:alert] %></p>
  <% end %>

  <div class="columns is-multiline">
    <% @products.each do |product| %>
      <div class="column is-4 is-flex">

        <div class="box is-flex is-flex-direction-column is-flex-grow-1" style="background-color: #7e83b6ff">

          <div class="is-flex">
            <!-- IMAGE LEFT -->
            <figure class="image is-128x128 mr-4">
              <% if product.image.attached? %>
                <%= image_tag url_for(product.image), style: "max-width: 100px; max-height:150px;", alt: product.name %>
              <% else %>
                <%= image_tag "", alt: "No image" %>
              <% end %>
            </figure>

            <!-- TEXT RIGHT -->
            <div class="content is-flex-grow-1">
              <p><strong><%=  product.name %></strong></p>
              <p><strong>Price: <%= product.price %></strong></p>
              <% if product.in_stock %>
                  <p style="font-size: 25px; color: #11ff00ff; -webkit-text-stroke: 1px black; " ><b >In Stock</b></p>
              <% else %>
                  <p style="font-size: 25px; color: #ff0000ff; -webkit-text-stroke: 1px black; "><b>Out of stock</b></p> 
              <% end %>

              <!-- Push Add button to bottom -->
              <div class="mt-auto">
                
                <p><%= link_to "View Product", product_path(product), class: "button is-small" %>
  </p>
              </div>
            </div>
          </div>

        </div>
      </div>
    <% end %>
    
  </div>

      <div class="is-flex is-justify-content-center" role="navigation" aria-label="pagination">
        <%= paginate @products, params: { query: params[:query], category_id: params[:category_id] } %>
      </div>
</div>

app/views/product/show.html.erb
<div style="min-height:93vh">
<%if @mode == :order_context%>
    <h1><%=link_to "Order", customer_path(session[:customer_id])%>>><%=link_to "Receipt", receipt_path(@customer.id,@order.id)%>>>Product</h1>
<%end%>
    <div style="display: flex; padding-left:100px; padding-right:100px; ">
        
        <div>
            <% if @product.image.attached? %>
                <%= image_tag url_for(@product.image), style: "width: 400px; height:auto;", alt: @product.name %>
            <% else %>
                <%= image_tag "", alt: "No image" %>
            <% end %>
        </div>
        <div>
            <h1 style="font-size: 50px ; font-weight: bold"><%= @product.name %></h1>
            <p style="font-size: 27px ; font-weight: bold">Price: <%= number_to_currency(@product.price) %></p>
            <% if @product.in_stock %>
                <p style="font-size: 27px; font-weight: bold">Status: <b style="color:green"> In Stock</b></p>
            <% else %>
                <p style="font-size: 27px; font-weight: bold">Status: <b style="color: red">Out of stock</b></p> 
            <% end %>
            <p style="font-size: 27px ; font-weight: bold">Category: <%= @product.category.name %></p>

        
            <% url = ""
            if session[:customer_id]
                url = addtocart_path(@product.id)
            else
                url = login_path
            end%>
            <%if @mode == :product_context%>
            
                <%= form_with url: url, class: "control", method: :get, local: true , data: { turbo: false } do |f| %>
                    <div class="actions">
                        <%= f.label :Quantity, style:"font-size: 27px ; font-weight: bold" %>
                        <%= f.number_field :quantity, style:"width:65px", value:"1", min:"1"%>
                    </div>
                    <br>
                    
                    <button class="button is-medium" style="margin-top:10px; color: white; font-weight: bold">Add To Cart</button>
                <% end %>
            <%end%>
        </div>
    </div>
    <h1 style="font-size: 50px ; font-weight: bold">Description:</h1>
    <div style="padding:50px">
        <p style="font-size: 20px ; font-weight: bold"><%= @product.description %></p>
    </div>
</div>